### PR TITLE
Rewrite political data code to allow additional countries

### PR DESCRIPTION
**Pull request by DylanMcCall**
This branch includes the first 80% of work on a major rewrite of political data, which will allow us to easily support campaigns in different countries. I'm making this pull request _now_ because I think it's a good starting point and it feels better to collaborate here. Please feel free to make changes in the proposed branch if you'd like :)

Campaigns now have a country field. To cut back on convoluted JavaScript, country and campaign type are selected together in a separate form page when creating a campaign. I added some migration code so that existing campaigns are updated with the country set to "us".

I'm adding a generic political data interface in call_server/political_data/countries/**init**.py. There is a DataProvider for the country as a whole, and a CampaignType class for different types of campaigns. This bit still needs some work (see below), and probably isn't ideal but at least gives us a smaller surface area for future improvements.

The US political data objects and constants have been moved to this new interface. Most of the existing code remains the same, for better or worse. Many constants have been replaced with properties in the political data objects themselves. There is no longer a USStateData class - everything is in the new USDataProvider and friends. For state campaigns, there is a USCampaignType_State.

This isn't quite ready for the real world, but it's getting close. There are many failing tests which need to be fixed and I haven't tested how this looks in a production environment. As a first priority we need to sort out the location property which is passed to CampaignType.all_targets. That will need some additional changes.

### CODE REVIEW

**Comment by DylanMcCall** [comment]
Just for reference, my plan for location stuff is as follows. Sadly not implemented (yet).

Add a new LocationProxy class which can be instantiated as any type of raw location input. That is: a zip code / postal code, an address, or a lat/lon. It has various methods to convert between those different types of locations and uses the geocoder implicitly when needed. The important bit is it knows when not to use the geocoder, such as when all we want is the zipcode and the user has provided exactly that.

We will need to update a bunch of functions to work with these Location objects instead of the existing assortment of zipcodes, geocoder output, or lat/lon variables. Instead we should convert to the specific type of location only when needed, such as when we are accessing Sunlight with a lat/lon or looking for a zipcode in a big CSV.

**Comment by jlev** [comment]
Sorry for mucking up this clean pull request, but I finally got around to merging with the latest. Tests now pass, and I'll be adding country-specific data sources for Canada later this week.

Thanks again for the code, it was a great basis for a more flexible and internationalized tool.

**Comment by jlev** [comment]
Added OpenNorth API in 5722f99fb61d6f69cb7d9a01e68b9fa963148fc8
Adjusted campaign creation flow and fixed validation in 64f45a6d6cac9a0abb44a311c4322de127651c8a

**Comment by DylanMcCall** [comment]
Yay! I'm glad this all worked for you. Thanks for the great thing, and for putting up with the somewhat unfinished state I left this branch in :)

**Pull request closed without merging**
